// Sprite sheet definitions for Tools/art/build-art.mjs.
// Each sheet is generated once by Codex (Art/Raw/<id>.png, committed) and sliced into Assets/Art/Generated/<out>/<name>.png.
// Item names match the prototype ids (SPECIES id = category + index, e.g. ed0) so game code can load by id.

// [id, Korean name, scientific name / motif, what it must look like]
export const MUSHROOMS = {
  ed: [
    ["ed0", "양송이", "Agaricus bisporus", "white button mushroom: smooth round white cap, short thick white stem"],
    ["ed1", "느타리", "Pleurotus ostreatus", "grey oyster mushroom: overlapping fan-shaped grey caps, white gills underneath, short side stem"],
    ["ed2", "표고", "Lentinula edodes", "shiitake: dark brown dome cap cracked into a white turtle-shell pattern, cream stem"],
    ["ed3", "팽이버섯", "Flammulina velutipes (cultivated enoki)", "bundle of long thin cream stems with tiny round caps"],
    ["ed4", "목이버섯", "Auricularia auricula-judae", "dark brown translucent jelly shaped like a human ear"],
    ["ed5", "새송이버섯", "Pleurotus eryngii", "king oyster: very thick white stem, small flat light-brown cap"],
    ["ed6", "먹물버섯", "Coprinus comatus", "shaggy ink cap: tall white cylindrical cap with shaggy scales, black ink dripping at the rim"],
    ["ed7", "말불버섯", "Lycoperdon perlatum", "white round puffball covered in tiny warts, a small puff of spores"],
    ["ed8", "꾀꼬리버섯", "Cantharellus cibarius", "golden-orange chanterelle trumpet with wavy rim and ridged false gills"],
    ["ed9", "덕다리버섯", "Laetiporus sulphureus", "chicken of the woods: stacked bright orange shelves with yellow edges"],
    ["ed10", "큰갓버섯", "Macrolepiota procera", "parasol: tall thin stem with a ring, wide beige cap with brown scales and a brown center bump"],
    ["ed11", "민자주방망이버섯", "Lepista nuda", "wood blewit: lilac-violet cap and gills, stout violet stem"],
    ["ed12", "기와버섯", "Russula virescens", "green-teal cap cracked into tile-like patches, white stem"],
    ["ed13", "만가닥버섯", "Hypsizygus marmoreus", "dense bunch of small marbled light-brown caps on white stems from one base"],
    ["ed14", "곰보버섯", "Morchella esculenta", "morel: honeycomb-pitted conical tan cap, hollow white stem"],
    ["ed15", "달걀버섯", "Amanita hemibapha (Caesar's mushroom)", "smooth orange-red cap rising out of a white egg-like sac, yellow stem"],
    ["ed16", "소혀버섯", "Fistulina hepatica", "beefsteak fungus: moist red tongue-shaped shelf"],
    ["ed17", "능이버섯", "Sarcodon aspratus", "dark brown funnel with rough upturned scales on top"],
    ["ed18", "송이버섯", "Tricholoma matsutake", "matsutake: thick white stem, brown fibrous cap, a faint golden glow (legendary)"],
    ["ed19", "송로버섯", "Tuber melanosporum", "black warty round truffle lump with a few golden sparkles (legendary)"],
    ["ed20", "싸리버섯", "Ramaria flava", "pale yellow coral fungus branching like a broom"],
    ["ed21", "달빛표고", "fantasy variant of Lentinula edodes", "shiitake with an indigo-blue cap whose cracks glow silver-white"],
    ["ed22", "주름버섯", "Agaricus campestris", "field mushroom: white cap tilted to show pink gills, short stem"],
    ["ed23", "바다송이", "fantasy variant of Tricholoma matsutake", "thick-stemmed matsutake with a sea-blue cap dusted with salt crystals and a tiny barnacle"],
    ["ed24", "벽돌먹물버섯", "fantasy variant of Coprinus comatus", "shaggy ink cap with a brick-red scaled cap and black inky rim"],
  ],
  md: [
    ["md0", "구름버섯", "Trametes versicolor", "turkey tail: thin overlapping fans with concentric grey, blue and tan bands"],
    ["md1", "치마버섯", "Schizophyllum commune", "small fuzzy white fan with split grey gills"],
    ["md2", "간버섯", "Pycnoporus cinnabarinus", "bright cinnabar-orange bracket shelf"],
    ["md3", "흰목이", "Tremella fuciformis", "snow fungus: white translucent jelly with ruffled petal lobes"],
    ["md4", "잎새버섯", "Grifola frondosa", "maitake: rosette of overlapping grey-brown leaf-like caps"],
    ["md5", "한입버섯", "Cryptoporus volvatus", "round chestnut-like orange-tan ball with a small pore hole"],
    ["md6", "복령", "Wolfiporia cocos", "brown bark-covered lump, one cut face showing white flesh"],
    ["md7", "저령", "Polyporus umbellatus", "many small round light-brown caps on branching stems like a bouquet"],
    ["md8", "꽃송이버섯", "Sparassis crispa", "cauliflower fungus: cream ruffled mass of curly lobes"],
    ["md9", "노루궁뎅이", "Hericium erinaceus", "lion's mane: white shaggy mass of hanging icicle spines"],
    ["md10", "말굽버섯", "Fomes fomentarius", "grey hoof-shaped hard bracket with concentric growth rings"],
    ["md11", "잔나비걸상버섯", "Ganoderma applanatum", "large flat brown semicircle shelf with a white rim"],
    ["md12", "목도리방귀버섯", "Geastrum triplex", "collared earthstar: brown star rays with a collar holding a round spore ball, a little spore puff"],
    ["md13", "소나무잔나비버섯", "Fomitopsis pinicola", "dark brown bracket with a red-orange and yellow banded edge"],
    ["md14", "영지버섯", "Ganoderma lucidum", "reishi: glossy lacquered red-brown kidney-shaped cap with a yellow rim and side stem"],
    ["md15", "상황버섯", "Phellinus linteus", "hard brown shelf with a bright yellow rim"],
    ["md16", "차가버섯", "Inonotus obliquus", "chaga: black cracked charcoal-like lump with rusty orange showing inside"],
    ["md17", "말똥진흙버섯", "Phellinus igniarius", "dark grey-brown hoof bracket with a finely cracked surface and brown rim"],
    ["md18", "동충하초", "Cordyceps militaris", "bright orange club-shaped fruiting bodies sprouting from a small pupa, soft glow (legendary)"],
    ["md19", "눈꽃동충하초", "Isaria japonica", "white powdery snowflake-like branches sprouting from a silkworm pupa, soft glow (legendary)"],
    ["md20", "자작나무버섯", "Fomitopsis betulina", "birch polypore: smooth white rounded shelf with a rolled edge on a strip of birch bark"],
    ["md21", "달빛동충하초", "fantasy variant of Cordyceps militaris", "pale blue glowing club-shaped fruiting bodies"],
    ["md22", "선녀낙엽버섯", "Marasmius oreades", "fairy ring mushroom: a small ring of tan caps with center bumps on thin stems"],
    ["md23", "산호버섯", "fantasy variant of Ramaria coral fungus", "pink coral-shaped branches with sea water droplets"],
    ["md24", "녹슨영지", "fantasy variant of Ganoderma lucidum", "reishi with a rusty iron-brown metallic cap and a bolt stuck in it"],
  ],
  ps: [
    ["ps0", "무당버섯", "Russula emetica", "bright red smooth cap, white gills and stem"],
    ["ps1", "노란다발", "Hypholoma fasciculare", "cluster of small sulfur-yellow caps"],
    ["ps2", "노란각시버섯", "Leucocoprinus birnbaumii", "lemon-yellow powdery bell cap on a slender yellow stem"],
    ["ps3", "맑은애주름버섯", "Mycena pura", "small delicate lilac-purple cap on a thin stem"],
    ["ps4", "이끼꽃버섯", "Gliophorus psittacinus", "parrot waxcap: slimy glossy dark-green small caps"],
    ["ps5", "비단빛깔때기버섯", "Clitocybe dealbata", "pure silky white funnel shape"],
    ["ps6", "땀버섯", "Inocybe fastigiata", "brown conical fibrous cap with a split edge"],
    ["ps7", "갈황색미치광이버섯", "Gymnopilus junonius", "cluster of orange-gold caps"],
    ["ps8", "광대버섯", "Amanita muscaria", "fly agaric: red cap with white warts, white stem with a skirt ring"],
    ["ps9", "뱀껍질광대버섯", "Amanita spissacea", "grey-brown cap with snakeskin scale pattern, snake-patterned stem"],
    ["ps10", "붉은싸리버섯", "Ramaria formosa", "salmon pink-orange coral fungus"],
    ["ps11", "알광대버섯", "Amanita phalloides", "death cap: olive-green cap, white skirt ring, white egg sac at the base"],
    ["ps12", "마귀곰보버섯", "Gyromitra esculenta", "false morel: brain-like wrinkled reddish-brown cap"],
    ["ps13", "독깔때기버섯", "Paralepistopsis acromelalga", "tan-orange funnel cap"],
    ["ps14", "화경버섯", "Omphalotus japonicus", "orange-brown fan with gills glowing green"],
    ["ps15", "개나리광대버섯", "Amanita subjunquillea", "forsythia-yellow cap, white ring and egg sac"],
    ["ps16", "마귀광대버섯", "Amanita pantherina", "panther cap: brown cap scattered with white warts"],
    ["ps17", "독우산광대버섯", "Amanita virosa", "destroying angel: all-white umbrella with ring and egg sac, faint eerie glow"],
    ["ps18", "붉은사슴뿔버섯", "Trichoderma cornu-damae", "poison fire coral: red finger-like horns (legendary)"],
    ["ps19", "갈색고리갓버섯", "Lepiota brunneoincarnata", "small cap with brown scales and a ring, faint glow (legendary)"],
    ["ps20", "흰가시광대버섯", "Amanita echinocephala", "white cap covered in spiky warts, ring"],
    ["ps21", "달빛애주름버섯", "fantasy variant of Mycena chlorophos", "small mycena glowing soft green"],
    ["ps22", "말똥버섯", "Panaeolus semiovatus", "grey-brown bell cap on a thin stem growing from a small dung pat"],
    ["ps23", "해파리버섯", "fantasy variant of a jelly fungus", "translucent purple jellyfish-like cap with dangling tendrils"],
    ["ps24", "콘크리트광대버섯", "fantasy variant of Amanita", "grey concrete-textured cracked amanita cap with a ring, bursting from a concrete chunk (legendary)"],
  ],
};

const CAT_NAME = { ed: "edible", md: "medicinal", ps: "poisonous" };

function mushroomSheet(cat, kind) {
  const list = MUSHROOMS[cat];
  const single = kind === "single";
  return {
    id: `mush_${kind}_${cat}`,
    rows: 5,
    cols: 5,
    out: `Mushrooms/${single ? "Single" : "Colony"}`,
    search: true,
    subject: single
      ? `25 different real ${CAT_NAME[cat]} mushroom species, one single mushroom (or its natural small group) per cell, drawn as encyclopedia icons that show the species' true shape clearly.`
      : `25 mushroom colonies of different species: each cell is a big chunky heap of MANY mushrooms of that one species packed tightly on a small mound of soil and moss, like a boss-sized clump. Massiveness and visual appeal matter more than detail.`,
    items: list.map(([id, kr, sci, look]) => [id, `${kr} (${sci}): ${look}`]),
  };
}

// Special mushroom critters (SPECIALS in the prototype): cap color c1, spots/accent c2, decoration on top of the cap.
export const CRITTERS = [
  ["fire", "orange-red cap (#ff7a2a) with yellow (#ffd34a) spots, a little flame on top"],
  ["spark", "yellow cap (#ffe03a) with pale yellow spots, a small lightning bolt on top"],
  ["dew", "sky-blue cap (#5fc8ff) with pale blue spots, a water droplet on top"],
  ["coin", "gold cap (#f5c518) with cream spots, a shiny coin on top"],
  ["star", "violet cap (#b07bff) with pale lilac spots, a little star on top"],
  ["leaf", "green cap (#5fc85a) with pale green spots, two sprout leaves on top"],
  ["moon", "deep navy cap (#3a4a8a) with pale yellow spots, a crescent moon on top"],
  ["wind", "mint cap (#5fd8c0) with white spots, two white wind swirls on top"],
  ["rock", "grey cap (#8a8a86) with light grey spots, a smooth pebble on top"],
  ["chest", "chestnut-brown cap (#a0602a) with beige spots, a small acorn on top"],
];

export const SHEETS = [
  ...["ed", "md", "ps"].map((c) => mushroomSheet(c, "single")),
  ...["ed", "md", "ps"].map((c) => mushroomSheet(c, "colony")),

  {
    id: "harvesters", rows: 3, cols: 3, out: "Harvesters",
    subject: "Pinball 'harvester' tokens for a mushroom-harvesting pinball game, seen from above. Each reads as a compact, roughly round spinning token (it rotates while it flies), chunky and readable at 40 px. Plus two small effect sprites.",
    items: [
      ["sam", "scythe harvester: a short wooden handle with a curved steel scythe blade, coiled into a round spinning shape"],
      ["saw", "shuriken harvester: four wide gunmetal blades around a round hub with a red gem in the middle"],
      ["mill", "circular saw harvester: a round steel disc ring with many small spinning teeth around it"],
      ["spore", "spore harvester: a round red-orange mushroom cap seen from above with cream spore dots"],
      ["bell", "bell harvester: a big acorn-shaped brass bell with an acorn-cap top"],
      ["coin", "coin harvester: a large old Korean brass coin (yeopjeon) with a square hole in the middle"],
      ["gold", "golden scythe harvester: the scythe harvester made of shining gold with sparkles (reward item)"],
      ["cloud_spore", "a soft puffy purple-grey spore cloud"],
      ["puff_dust", "a small soft white dust puff"],
    ],
  },
  {
    id: "icons_a", rows: 5, cols: 5, out: "Icons",
    subject: "Square game UI icons, each a single bold object centered in its cell, consistent size.",
    items: [
      ["gold", "a shiny gold coin"],
      ["ed", "an edible mushroom icon: cream stem with a round ORANGE cap"],
      ["md", "a medicinal mushroom icon: cream stem with a round GREEN cap"],
      ["ps", "a poisonous mushroom icon: cream stem with a round PURPLE cap with white dots"],
      ["tax", "a tax bill: a paper scroll with lines and a red stamp"],
      ["gem", "mycelite: a bumpy purple stone with glowing teal mycelium threads and a tiny mushroom sprout on top"],
      ["spore", "a small tied burlap sack with tiny spores floating up out of it"],
      ["clock", "a round brass stopwatch"],
      ["w_clear", "sunny weather: a smiling round sun"],
      ["w_rain", "light rain: a soft cloud with a few rain drops"],
      ["w_moon", "full moon night: a big glowing full moon"],
      ["w_autumn", "autumn leaves: two falling orange maple leaves"],
      ["w_thunder", "thunderstorm: a dark cloud with a yellow lightning bolt"],
      ["w_rainbow", "rainbow arching over a small cloud"],
      ["w_fog", "thick fog: layered grey mist bands"],
      ["w_wind", "spore wind: purple swirling wind with spores"],
      ["w_storm", "heavy rain storm: a big wave with heavy rain"],
      ["w_cold", "cold snap: an icy blue snowflake"],
      ["w_drought", "drought: cracked dry earth under a hot sun"],
      ["t_forest", "forest region: two round pine trees"],
      ["t_night", "moonlit night region: a crescent moon over dark trees"],
      ["t_field", "field region: golden wheat stalks"],
      ["t_sea", "sea region: a curling blue wave over sand"],
      ["t_ruins", "mushroom ruins region: a ruined house with a giant mushroom growing through it"],
      ["trophy", "a golden trophy cup"],
    ],
  },
  {
    id: "icons_b", rows: 5, cols: 5, out: "Icons",
    subject: "Square game skill and UI icons, each a single bold object centered in its cell, consistent size.",
    items: [
      ["s_accel", "acceleration: a speeding round token with wind speed lines"],
      ["s_sharpen", "sharpen: a whetstone sharpening a shining blade with a spark"],
      ["s_split", "split: one glowing orb splitting into two with sparkles"],
      ["s_sip", "sip of time: an hourglass with a little sip cup"],
      ["s_clear", "clear spore shield: a translucent cyan bubble"],
      ["s_burst", "spore burst: an orange explosion of spores"],
      ["s_tspore", "time spore: a spore with a small clock face"],
      ["s_clone", "clone harvester: two overlapping spinning blades, one ghostly"],
      ["s_magnet", "mushroom magnet: a red horseshoe magnet"],
      ["s_bolt", "chain lightning: a zigzag yellow lightning bolt"],
      ["s_tornado", "tornado: a mint-green whirlwind"],
      ["s_shock", "shockwave: concentric orange rings bursting outward"],
      ["s_device", "forest device: a small tree stump with a sprout"],
      ["s_pierce", "pierce: a short dagger piercing through"],
      ["s_fest", "bountiful harvest: a golden wheat sheaf"],
      ["s_blade", "spinning blade: a four-point steel blade star"],
      ["s_kid", "kid harvester: a tiny blue spinning token"],
      ["core_ed", "money bag full of gold"],
      ["core_md", "a target with an arrow in the bullseye"],
      ["core_ps", "two crossed swords"],
      ["lock", "a closed brass padlock"],
      ["book", "an open mushroom encyclopedia book"],
      ["pause", "a round wooden pause button"],
      ["star", "a golden star"],
      ["medal", "a gold medal with a ribbon"],
    ],
  },
  {
    id: "props", rows: 4, cols: 4, out: "Props",
    subject: "Top-down game field props and particles for a forest pinball field, seen from directly above.",
    items: [
      ["stump", "a round tree stump bumper seen from above, cut face with growth rings, bark rim"],
      ["mole", "a mole hole: a dark round hole in a ring of dug-up dirt, seen from above"],
      ["acorn_off", "an acorn switch: a brown acorn lying on the ground, seen from above"],
      ["acorn_on", "the same acorn switch glowing golden-yellow, lit up"],
      ["moss", "a wide rounded-rectangle patch of soft bright moss with tiny glowing specks (flat, top-down, even border all around)"],
      ["stream", "a wide rounded-rectangle patch of clear blue stream water with small white ripples (flat, top-down, even border all around)"],
      ["mound", "a small round mound of soil and moss, seen from slightly above (base for a mushroom heap)"],
      ["warn_shadow", "a dark oval ground shadow with cracks (where something giant will burst out)"],
      ["clover", "a small clover sprig"],
      ["flowers", "a tiny cluster of white and yellow wild flowers"],
      ["pebbles", "three small rounded pebbles"],
      ["leaf", "a single orange autumn leaf"],
      ["snowflake", "a single small white snowflake"],
      ["sparkle", "a four-point white sparkle"],
      ["sparkle_gold", "a four-point golden sparkle"],
      ["crack", "dark crack lines decal on a transparent background"],
    ],
  },
  {
    id: "ui_kit", rows: 3, cols: 3, out: "UI",
    subject: "A UI kit of EMPTY interface frames and buttons (no icons, no symbols, no text inside them) for a cozy wooden game interface, drawn flat and front-facing. Panels and buttons must have even, uniform borders on all sides so they can be 9-sliced.",
    items: [
      ["panel_wood", "a square wooden frame panel: thick rounded dark-brown wood border (#7a4f2e) around a cream paper center (#f6ead2)"],
      ["panel_paper", "a plain square cream paper card (#fffaf0) with a thin tan rounded border"],
      ["btn_wood", "a rounded rectangle button of light cream-to-tan wood with a dark brown outline"],
      ["btn_go", "a rounded rectangle button of glossy honey-yellow with a dark brown outline"],
      ["btn_danger", "a rounded rectangle button of coral-red with a dark brown outline"],
      ["badge_round", "a round wooden badge with a cream center"],
      ["bar_log", "a long thin horizontal wooden log platform with a small green leaf at each end (very wide and short)"],
      ["sign_arrow", "a wooden signpost arrow board pointing right"],
      ["basket", "a woven wooden harvest basket seen from the front, open top"],
    ],
  },
  {
    id: "bg_forest", kind: "image", out: "Backgrounds/bg_forest.png",
    prompt: "Wide landscape 16:9 game background: top-down view of a forest-floor pinball field. Soft mossy green grass with a few clovers and gentle light patches. All four edges are framed by a thin border of rounded grey rocks and roots (about 4% of the width). The middle is calm and fairly plain so small game objects read clearly. No mushrooms, no characters, no text, no UI.",
  },
  {
    id: "bg_title", kind: "image", out: "Backgrounds/bg_title.png",
    prompt: "Wide landscape 16:9 game title background: a ruined village at dusk under a purple-pink sky, overrun by giant cartoon mushrooms (a red one with white dots, a lilac one, an orange one, a green one, a brown one) towering behind the houses, small mushrooms on the rooftops, spores drifting in the air. Keep the lower-left corner and the center fairly open for a character and a title panel. No text, no characters.",
  },
  {
    id: "grandpa_full", rows: 1, cols: 1, out: "Characters/Grandpa",
    subject: "One full-body character, front three-quarter view, standing, cute chibi proportions (big head) like Cookie Run: Kingdom characters.",
    items: [["grandpa_ref", "a veteran mushroom-hunter grandpa: worn brown leather hunting hat with a feather, a scar over one eye, a braided grey beard, a long olive coat with a fur collar, a bandolier of little spore vials across the chest, dried mushroom trophies and a short dagger at the belt, a big scythe resting on his shoulder, sturdy boots, kind sparkly eyes"]],
  },
  {
    id: "grandpa_parts", rows: 4, cols: 4, out: "Characters/Grandpa", refs: ["Art/Raw/grandpa_full.png"],
    subject: "Cut-out animation parts of the SAME mushroom-hunter grandpa as the attached reference, all drawn at the same scale, each part separate with a little extra overlap at the joints so they can be rigged. Neutral pose, front three-quarter view.",
    items: [
      ["hat", "the leather hunting hat with the feather"],
      ["head", "the head without the hat: face with the eye scar, ears, braided grey beard, no eyes drawn (blank eye area)"],
      ["eyes_open", "a pair of kind open eyes"],
      ["eyes_sparkle", "a pair of sparkling excited eyes with star highlights"],
      ["eyes_closed", "a pair of closed eyes (blink)"],
      ["torso", "the torso in the long olive coat with fur collar, spore vial bandolier and belt with mushroom trophies and dagger, no arms, no legs"],
      ["coat_tail", "the lower hem of the coat (tail flap)"],
      ["upper_arm_back", "the upper arm (shoulder to elbow) of the arm that holds the scythe"],
      ["lower_arm_back", "the forearm and hand (elbow to fist) of the arm that holds the scythe"],
      ["upper_arm_front", "the upper arm (shoulder to elbow) of the free arm"],
      ["lower_arm_front", "the forearm and open hand (elbow to hand) of the free arm"],
      ["leg_left", "the left leg with boot"],
      ["leg_right", "the right leg with boot"],
      ["scythe", "the big scythe alone"],
      ["brow_left", "a bushy grey eyebrow"],
      ["brow_right", "a bushy grey eyebrow, mirrored"],
    ],
  },
  {
    id: "critters_full", rows: 2, cols: 5, out: "Characters/Critters",
    subject: "Ten cute chibi mushroom-critter characters of one family, front view, standing: each has a round cream face/body with big round eyes, a small smile and rosy cheeks, little brown feet, and a big mushroom cap on top. Same body shape for all; only the cap colors and the decoration differ.",
    items: CRITTERS.map(([id, look]) => [`${id}_ref`, look]),
  },
  {
    id: "critter_parts", rows: 4, cols: 5, out: "Characters/Critters", refs: ["Art/Raw/critters_full.png"],
    subject: "Cut-out animation parts for the mushroom critters in the attached reference, all at the same scale, front view. Caps include their decoration. Body parts are shared by all critters.",
    items: [
      ...CRITTERS.map(([id, look]) => [`cap_${id}`, `the mushroom cap only: ${look}`]),
      ["body", "the shared round cream face/body WITHOUT eyes or mouth"],
      ["eyes_open", "a pair of big round shiny eyes"],
      ["eyes_closed", "a pair of closed happy eyes (^ ^)"],
      ["eyes_x", "a pair of dizzy swirl eyes"],
      ["mouth_smile", "a small smiling mouth"],
      ["mouth_open", "a small open 'o' mouth"],
      ["blush", "a pair of rosy cheek blush ovals"],
      ["foot", "one little brown foot"],
      ["sweat", "a small sweat drop"],
      ["heart", "a small pink heart"],
    ],
  },
  // ===== shop · farm · skins (ported together, 2026-10-07) =====
  {
    id: "npcs", rows: 2, cols: 4, out: "Characters/NPC", refs: ["Art/Raw/grandpa_full.png"],
    subject: "Bust portraits (head and shoulders only, front three-quarter view, friendly smile, modest everyday clothing) of eight villagers of a cozy mushroom village, for a quest board. Same art style as the mushroom-hunter grandpa reference. Each portrait is a clean cut-out on a fully transparent background: no glow, no vignette, no backdrop. Wide sheet: 2 rows of 4 portraits.",
    items: [
      ["baker", "Milsun, an old granny baker: grey hair in a bun, round glasses, pink dress with a white apron"],
      ["herb", "Gamcho, an old herbalist grandpa: bald head, long white beard, round glasses, green robe"],
      ["smith", "Musoe, a burly blacksmith uncle: short dark hair, stubble, red headband, brown leather apron"],
      ["kid", "Dotori, a little boy mushroom hunter: brown hair, orange cap, freckles, sky-blue shirt"],
      ["inn", "Dallae, a cheerful middle-aged innkeeper woman: long brown hair tied with a purple scarf, modest high-collared purple dress with an apron"],
      ["dr", "Dr. Pojarin, a scientist: messy silver hair, round glasses, white lab coat"],
      ["merch", "Geumbok, a plaza merchant: short black hair, curled mustache, dark top hat, red vest"],
      ["ranger", "Solip, a forest ranger woman: long brown hair, olive ranger hat and green uniform"],
    ],
  },
  {
    id: "farm_props", rows: 3, cols: 4, out: "Farm/Props",
    subject: "Props for a cozy mushroom farm seen from a slight top-down 3/4 view, each standing on its own base, drawn at the same scale as each other.",
    items: [
      ["dc_table", "a big mushroom-cap table with two small mushroom stools"],
      ["dc_fire", "a brazier shaped like a mushroom cap with a cozy fire burning in it"],
      ["dc_lamp", "a pair of glowing mushroom lanterns on short posts"],
      ["dc_bed", "a wooden flower bed planter full of colorful flowers"],
      ["dc_swing", "a small swing hanging between two mushroom-shaped trees"],
      ["dc_well", "a small fountain whose top is a mushroom cap spouting water"],
      ["dc_house", "a little red mushroom cottage with a round window and a door"],
      ["dc_statue", "a statue carved from glowing teal mycelium crystal on a stone base"],
      ["stove", "a cute kitchen stove hearth with a bubbling pot on top"],
      ["counter", "a wooden kitchen prep counter with a cutting board"],
      ["dining", "a round wooden dining table with a checkered cloth"],
      ["scarecrow", "a friendly scarecrow wearing a mushroom-cap hat"],
    ],
  },
  {
    id: "farm_icons", rows: 5, cols: 5, out: "Farm/Icons",
    subject: "Small bold game icons for a cozy mushroom farm and kitchen, each a single object centered in its cell, readable at 32 px.",
    items: [
      ["req_water", "a blue water droplet"], ["req_pet", "a gently patting open hand"], ["req_song", "two musical notes"],
      ["req_snack", "a round cookie"], ["req_gift", "a wrapped gift box with a red ribbon"],
      ["fx_heart", "a pink heart"], ["fx_zzz", "sleepy letters Z z made of fluffy cloud shapes"], ["fx_surprise", "a yellow exclamation burst"], ["fx_note", "a single music note"],
      ["tool_knife", "a small kitchen knife"], ["tool_ladle", "a wooden ladle"], ["tool_plate", "an empty white plate"],
      ["dish_soup", "a bowl of creamy mushroom soup"], ["dish_songi", "a bowl of rice topped with sliced matsutake"],
      ["dish_tea", "a cup of green herbal tea"], ["dish_reishi", "a small potion bottle of reddish-brown reishi tonic"],
      ["dish_cure", "a clay bowl of green herbal detox broth with leaves"], ["dish_venom", "purple poison-mushroom skewers"],
      ["dish_fog", "a pot of purple misty stew"], ["dish_hotpot", "a hot pot with three colors of mushrooms"],
      ["dish_jap", "a plate of glass noodles with wood-ear mushrooms"], ["dish_truffle", "a plate of risotto with shaved black truffle"],
    ],
  },
  {
    id: "field", rows: 3, cols: 4, out: "Farm/Field",
    subject: "Tiles and tools for a mushroom farm field. The four tile items are FLAT, straight top-down (orthographic, seen from directly above) SQUARE soil plots with no side faces and no perspective, all exactly the same size, each filling its whole cell edge to edge so they tile seamlessly in a square grid. Crops and tools are single objects. Wide sheet: 3 rows of 4.",
    items: [
      ["tile_grass", "a square plot of untouched grassy ground"],
      ["tile_soil", "a square plot of freshly tilled dark brown soil with neat furrows"],
      ["tile_sprout", "a square plot of tilled soil with a tiny mushroom sprout poking out"],
      ["tile_grow", "a square plot of tilled soil with small young mushrooms growing"],
      ["crop_ed", "a ripe cluster of orange edible mushrooms ready to harvest, glowing a little"],
      ["crop_md", "a ripe cluster of green medicinal mushrooms ready to harvest, glowing a little"],
      ["crop_ps", "a ripe cluster of purple poison mushrooms ready to harvest, glowing a little"],
      ["tool_0", "an old worn wooden hoe"], ["tool_1", "an iron hoe"], ["tool_2", "a shiny silver hoe"],
      ["tool_3", "a hoe with a glowing teal mycelium-crystal blade"], ["tool_4", "a legendary golden pitchfork"],
    ],
  },
  {
    id: "critter_acc", rows: 3, cols: 4, out: "Characters/Critters/Acc", refs: ["Art/Raw/critters_full.png"],
    subject: "Accessories and hats sized to fit the mushroom critters in the attached reference, each drawn alone in front view, to be layered on a critter's cap or face.",
    items: [
      ["bandana", "a red pirate bandana with white dots, tied at the side"], ["headphones", "big neon headphones"],
      ["scarf", "a cozy white knitted scarf"], ["tophat", "a small black top hat with a gold band"],
      ["halo", "a glowing golden halo ring"], ["flower", "a pink cherry-blossom flower hairpin"],
      ["sunglasses", "black cool sunglasses"], ["cloud", "a small fluffy white cloud"],
      ["crown", "a small jeweled golden crown"], ["bow", "a big pink ribbon bow"],
      ["chef", "a white chef toque"], ["straw", "a straw farmer hat with a red band"],
    ],
  },
  {
    id: "critter_skin_caps", rows: 2, cols: 5, out: "Characters/Critters", refs: ["Art/Raw/critter_parts.png"],
    subject: "Recolored skin versions of the mushroom caps in the attached critter parts sheet. Exactly the same cap shape, size and line style as the caps there, only the colors and pattern change, and NO decoration on top.",
    items: [
      ["skin_fire", "lava cap: dark red (#b8261a) with glowing orange (#ffb02a) cracks and spots"],
      ["skin_spark", "neon cap: hot pink (#ff4fd8) with cyan (#7dfcff) spots"],
      ["skin_dew", "snowflake cap: icy white (#eef6ff) with pale blue (#a8d8ff) snowflake spots"],
      ["skin_coin", "rich cap: deep green (#2a6a3a) with gold (#ffd84a) spots"],
      ["skin_star", "galaxy cap: midnight blue (#1e1e52) with pale yellow (#fff07a) star spots"],
      ["skin_leaf", "cherry-blossom cap: pink (#ffb0c8) with white petal spots"],
      ["skin_moon", "sun cap: bright orange (#ffa62a) with pale yellow (#fff4b0) spots"],
      ["skin_wind", "cloud cap: white with light blue (#cfe6ff) spots"],
      ["skin_rock", "gem cap: aqua crystal (#6ad0e0) with faceted shine"],
      ["skin_chest", "strawberry-chocolate cap: chocolate brown (#5a3420) with pink (#ff8ab0) spots"],
    ],
  },
  {
    id: "harvester_skins", rows: 2, cols: 4, out: "Harvesters", refs: ["Art/Raw/harvesters.png"],
    subject: "Skin versions of the pinball harvester tokens in the attached reference: exactly the same shapes and size, only recolored. Clean cut-outs on a fully transparent background: NO glow, NO aura, NO colored background. Wide sheet: 2 rows of 4.",
    items: [
      ["hs_sam", "cherry-blossom scythe: pink blade, pale wood handle"],
      ["hs_saw", "obsidian shuriken: near-black blades with violet edges and a purple hub"],
      ["hs_mill", "ice saw: pale icy blue disc with white edges"],
      ["hs_spore", "galaxy spore: deep indigo cap with yellow star dots"],
      ["hs_bell", "golden bell: shining gold bell with a dark gold cap"],
      ["hs_coin", "jade coin: jade green coin with a darker green ring"],
      ["hs_gold", "dragon scythe: red blade with a gold edge and a dark handle"],
    ],
  },
  {
    id: "bg_ranch", kind: "image", out: "Backgrounds/bg_ranch.png",
    prompt: "Wide landscape 16:9 game background, slight top-down 3/4 view: a cozy mushroom-farm ranch yard. A big grassy pen enclosed by a low wooden fence fills the middle (roughly 13% to 87% of the width and 28% to 84% of the height), with a dirt path running from the bottom edge into the pen. Behind the fence at the top: rolling hills, a few giant mushrooms and a warm sky. The inside of the pen is calm and fairly plain so small characters read clearly. No characters, no buildings inside the pen, no text, no UI.",
  },
  {
    id: "bg_field", kind: "image", out: "Backgrounds/bg_field.png",
    prompt: "Wide landscape 16:9 game background, slight top-down 3/4 view: a mushroom farm field area. Left two-thirds: a large plain flat dirt-and-grass clearing where a square crop plot will be drawn (keep it empty and even). Right third: a small wooden tool shed and a stack of hay. Wooden fence along the top, sunny day, warm colors. No crops, no characters, no text, no UI.",
  },
  // ===== 농장 개편 (다이아몬드 · 건축 · 자동 수확) =====
  {
    id: "farm_build_icons", rows: 1, cols: 4, out: "Icons",
    subject: "Small bold game icons for a cozy mushroom farm, each a single object centered in its cell, readable at 32 px.",
    items: [
      ["dia", "a sparkling cut diamond gem in pink-violet and cyan facets (premium cosmetic currency, clearly different from a green crystal)"],
      ["hammer", "a small wooden-handled builder's hammer"],
      ["auto_harvest", "a woven basket overflowing with mushrooms and gold coins"],
      ["build", "a little wooden house frame under construction with a hammer leaning on it"],
    ],
  },
  {
    id: "critter_hardhat", rows: 1, cols: 1, out: "Characters/Critters/Acc", refs: ["Art/Raw/critters_full.png"],
    subject: "A hat sized to fit the mushroom critters in the attached reference, drawn alone in front view, to be layered on a critter's cap.",
    items: [["hardhat", "a small yellow construction hard hat with a front brim"]],
  },
  {
    id: "auto_reward", rows: 1, cols: 1, out: "Farm/Props",
    subject: "A single large reward illustration for an idle-harvest reward popup.",
    items: [["auto_reward", "a big open wooden treasure chest overflowing with gold coins, glowing orange mushrooms, teal mycelium crystals and sparkling pink-violet diamonds, with coins spilling onto the ground"]],
  },
  {
    id: "bg_kitchen", kind: "image", out: "Backgrounds/bg_kitchen.png",
    prompt: "Wide landscape 16:9 game background, slight top-down 3/4 view: the inside of a cozy little mushroom-village kitchen restaurant. Warm wooden walls with shelves of jars and hanging herbs at the top, a window, and a wooden plank floor filling the lower two-thirds, kept plain so furniture and characters can be placed on it. No furniture on the floor, no characters, no text, no UI.",
  },
];
